### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yashchoudhary8955**

### CODE REVIEW

**Comment by aredridel** [comment]
I'm going to decline this pull request as it is not adding value to the project. If you have actual concerns with the README or its grammar, let's have a conversation first.

**Comment by yashchoudhary8955** [comment]
> I'm going to decline this pull request as it is not adding value to the project. If you have actual concerns with the README or its grammar, let's have a conversation first
thx sir,
sir i was correcting grammer why u declined my request

**Comment by aredridel** [comment]
Because it is a low-value pull request, changing single words, in a language with pretty broad senses of what is and is not grammatical. It's almost as though trying to get pull requests accepted were the goal, rather than advancing the project — on a project, I might add, that has largely been superseded by `parse5`

**Comment by aredridel** [comment]
Also, for the record **not sir**.

**Pull request closed without merging**
